version: "3"

services:
  postgres:
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: "raidhub"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./raidhub-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready raidhub -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  raidhub-postgres:
